import numpy as np
from scipy.constants import speed_of_light as SPEED_OF_LIGHT
from copy import copy

META_SETTINGS = {}
META_SETTINGS["LOW_UE_DENSITY"] = 50e-6 # UEs per square kilometer
META_SETTINGS["HIGH_UE_DENSITY"] = 150e-6 # UEs per square kilometer
META_SETTINGS["LOW_TARGET_DENSITY"] = 150e-6 # targets per square kilometer
META_SETTINGS["HIGH_TARGET_DENSITY"] = 300e-6 # targets per square kilometer
META_SETTINGS["SENSOR_DENSITIES"] = np.array([5, 15]) * 1e-6 # sensors per square kilometer

STANDARD_SCENARIO = copy(META_SETTINGS)

# Channel parameters
STANDARD_SCENARIO["NUMEROLOGY"] = 3 # 5G NR numerology index (0 to 4), determines subcarrier spacing and symbol duration
STANDARD_SCENARIO["OFDM_SYMBOLS_PER_SLOT"] = 14 # Number of OFDM symbols per slot for normal cyclic prefix
STANDARD_SCENARIO["COHERENCE_INTERVAL_DURATION"] = 512 # OFDM SYMBOLS, duration of the coherence processing interval, defined for speeds of up to 50 m/s
STANDARD_SCENARIO["PATH_LOSS_EXP"] = 2.4 # Sensing path loss exponent 
STANDARD_SCENARIO["UE_GAIN_DB"] = 0 # dBi
STANDARD_SCENARIO["BS_TOTAL_POWER_DB"] = 35


# From TR 38.901, Table 7.4.1-1, for UMi Street Canyon
STANDARD_SCENARIO["BS_HEIGHT"] = 25 # meters
STANDARD_SCENARIO["VEHICLE_HEIGHT"] = 1.5 # meters, assuming vehicles are similar in height to UEs
STANDARD_SCENARIO["SENSOR_HEIGHT"] = 25 # meters
STANDARD_SCENARIO["SHADOWING_STD_DEV"] = 4.0 # dB, scale parameter for Shadowing fading (normal distribution with mean 0 dB)

# From 3GPP TR 38.901, Table 7.8-1
STANDARD_SCENARIO["NOISE_FIGURE_DB"] = 9 # dB, UT noise figure 

# To fix the modeling artifact of unrealistic angle errors
STANDARD_SCENARIO["TARGET_SENSOR_ANGLE_CORRECTION_DEG"] = 15

# From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks
STANDARD_SCENARIO["SENSOR_POWER_DB"] = 23 # Sensor uplink transmit power in dBm

# From TR 38.901, Table 7.3-1
STANDARD_SCENARIO["MAX_ANTENNA_ELEMENT_GAIN_DB"] = 8 # dBi0)
STANDARD_SCENARIO["FRONT_TO_BACK_RATIO_DB"] = 30 # dB
STANDARD_SCENARIO["SINGLE_ELEMENT_HPBW_DEG"] = 65 # degrees

# From TR 38.901, Table 7.8-1
STANDARD_SCENARIO["BS_BORESIGHTS"] = np.deg2rad([30,150,270]) 

# Scenario input
STANDARD_SCENARIO["CELL_RANGE"] = 400 # meters
STANDARD_SCENARIO["N_SECTORS"] = 3 # Number of sectors in the cell

# Slicing parameters
STANDARD_SCENARIO["REQ_THROUGHPUT"] = 24e6 # bps, SLA requirement for UE throughput
STANDARD_SCENARIO["REQ_POSITION_ERROR"] = 0.1 # meters, SLA requirement for target sensing accuracy
STANDARD_SCENARIO["COMM_SLICE_WEIGHT"] = 0.5 # Weight of the communication slice
STANDARD_SCENARIO["SENSING_SLICE_WEIGHT"] = 0.5 # Weight of the sensing slice

# Sensor parameters
STANDARD_SCENARIO["SENSING_DEMAND_PER_VEHICLE"] = 29.72e3 # bps, amount of sensing data generated by sensing each vehicle
STANDARD_SCENARIO["SENSOR_DENSITY"] = META_SETTINGS["SENSOR_DENSITIES"][0] # sensors per square kilometer

# Bandwidth allocation
STANDARD_SCENARIO["UPLINK_PRBS"] = 1 # Number of PRBs allocated for uplink communication (sensing data transmission from sensors to BS)

STANDARD_SCENARIO["REALIZATIONS"] = 1 # Default number of realizations; overwritten by the scripts





BS_SETUPS = ["mmWave"]
DEMAND_SETUPS = ["LOW_UE_LOW_TARGET", "LOW_UE_HIGH_TARGET", "HIGH_UE_LOW_TARGET", "HIGH_UE_HIGH_TARGET"]

SCENARIOS = {
    bs: {
        demand: copy(STANDARD_SCENARIO) for demand in DEMAND_SETUPS
    } for bs in BS_SETUPS
}

for bs in BS_SETUPS:
    SCENARIOS[bs]["LOW_UE_LOW_TARGET"]["UE_DENSITY"] = META_SETTINGS["LOW_UE_DENSITY"]
    SCENARIOS[bs]["LOW_UE_LOW_TARGET"]["TARGET_DENSITY"] = META_SETTINGS["LOW_TARGET_DENSITY"]

    SCENARIOS[bs]["HIGH_UE_LOW_TARGET"]["UE_DENSITY"] = META_SETTINGS["HIGH_UE_DENSITY"]
    SCENARIOS[bs]["HIGH_UE_LOW_TARGET"]["TARGET_DENSITY"] = META_SETTINGS["LOW_TARGET_DENSITY"]

    SCENARIOS[bs]["LOW_UE_HIGH_TARGET"]["UE_DENSITY"] = META_SETTINGS["LOW_UE_DENSITY"]
    SCENARIOS[bs]["LOW_UE_HIGH_TARGET"]["TARGET_DENSITY"] = META_SETTINGS["HIGH_TARGET_DENSITY"]

    SCENARIOS[bs]["HIGH_UE_HIGH_TARGET"]["UE_DENSITY"] = META_SETTINGS["HIGH_UE_DENSITY"]
    SCENARIOS[bs]["HIGH_UE_HIGH_TARGET"]["TARGET_DENSITY"] = META_SETTINGS["HIGH_TARGET_DENSITY"]

for demand in DEMAND_SETUPS:
    SCENARIOS["mmWave"][demand]["CARRIER_FREQ_HZ"] = 28e9 # Hz, mmWave carrier frequency
    SCENARIOS["mmWave"][demand]["N_ANTENNA_ELEMENTS"] = 16 # Number of antenna elements in a ULA for mmWave
    SCENARIOS["mmWave"][demand]["N_PRBS"] = 42 # Number of Physical Resource Blocks (PRBs) for mmWave
    SCENARIOS["mmWave"][demand]["N_SENSOR_ANTENNA_ELEMENTS"] = 16 # Number of antenna elements in a sensor


# Derived parameters
for demand in DEMAND_SETUPS:
    for bs in BS_SETUPS:
        SCENARIOS[bs][demand]["SLOTS_PER_FRAME"] = 10 * 2** SCENARIOS[bs][demand]["NUMEROLOGY"] # Number of slots per coherence processing interval (10 ms)
        SCENARIOS[bs][demand]["SUBCARRIER_SPACING_HZ"] = 15e3*2** SCENARIOS[bs][demand]["NUMEROLOGY"] # Hz, subcarrier spacing
        SCENARIOS[bs][demand]["PRB_SIZE_HZ"] = 12 *  SCENARIOS[bs][demand]["SUBCARRIER_SPACING_HZ"] # Hz, size of each PRB

        SCENARIOS[bs][demand]["BANDWIDTH_HZ"] = SCENARIOS[bs][demand]["PRB_SIZE_HZ"] * SCENARIOS[bs][demand]["N_PRBS"] # Total bandwidth for all PRBs
        SCENARIOS[bs][demand]["WAVELENGTH"] = SPEED_OF_LIGHT / SCENARIOS[bs][demand]["CARRIER_FREQ_HZ"]
        SCENARIOS[bs][demand]["ANTENNA_SPACING"] = SCENARIOS[bs][demand]["WAVELENGTH"] / 2 # meters
        SCENARIOS[bs][demand]["SENSOR_ANTENNA_SPACING"] = SCENARIOS[bs][demand]["WAVELENGTH"] / 2 # meters

        SCENARIOS[bs][demand]["BS_BEAM_POWER_DB"] = STANDARD_SCENARIO["BS_TOTAL_POWER_DB"] - 10 * np.log10(SCENARIOS[bs][demand]["N_ANTENNA_ELEMENTS"])

        # Assuming the number of beams is the same as the number of antenna elements for simplicity
        SCENARIOS[bs][demand]["N_BEAMS_PER_SECTOR"] = SCENARIOS[bs][demand]["N_ANTENNA_ELEMENTS"]

        # For forced allocation
        SCENARIOS[bs][demand]["TARGET_SENSING_PRBS"] = SCENARIOS[bs][demand]["N_PRBS"] - SCENARIOS[bs][demand]["UPLINK_PRBS"]
        SCENARIOS[bs][demand]["UE_SENSING_PRBS"] = SCENARIOS[bs][demand]["N_PRBS"] - SCENARIOS[bs][demand]["UPLINK_PRBS"]
        SCENARIOS[bs][demand]["UE_COMM_PRBS"] = 0
