# Simulation design philosophy:
# All values generated by the simulation should be stored in a dictionary, which can be accessed by the user
# A method cannot call another public method, but can access the values generated by another method through the dictionary
# If a method depends on the values generated by another method, that is something the user should be aware of and should call the methods in the correct order
# Every calculation needs to be vectorized, preferably using numpy, to ensure that the simulation runs efficiently

from .utils import *
import numpy as np
from scipy.constants import speed_of_light as SPEED_OF_LIGHT

class Simulation:
    def __init__(self):
        self.data = {}

    # ----------------------------------------------
    # REALIZATION OF RANDOM VARIABLES 
    # ----------------------------------------------

    # From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks, Muhammad Saad Zia et al.
    # In their paper, BS positions are generated as a homogeneous Poisson Point Process
    # We consider that sensors follow the same distribution as BSs
    def gen_sensor_pos_random(self, no_warning=False):
        cell_area = np.pi*self.data["CELL_RANGE"]**2
        n_sensors = np.ceil(np.random.poisson(self.data["SENSOR_DENSITY"]*cell_area, (self.data["REALIZATIONS"],)))
        if np.any(n_sensors == 0):
            if not no_warning:
                print("Warning: Some realizations have zero sensors. Consider increasing the sensor density. Adding 1 sensor to them...")
            n_sensors[n_sensors == 0] = 1
        max_n_sensors = int(np.max(n_sensors))
        self.data["sensor_range"] = np.random.uniform(10, self.data["CELL_RANGE"], (self.data["REALIZATIONS"], max_n_sensors))
        self.data["sensor_angle"] = np.random.uniform(0, 2*np.pi, (self.data["REALIZATIONS"], max_n_sensors))
        self.data["sensor_x"] = self.data["sensor_range"] * np.cos(self.data["sensor_angle"])
        self.data["sensor_y"] = self.data["sensor_range"] * np.sin(self.data["sensor_angle"])
        self.data["sensor_boresights"] = np.random.uniform(0, 2*np.pi, (self.data["REALIZATIONS"], max_n_sensors))

        idx = np.arange(max_n_sensors)
        self.data["sensor_mask"] = idx < n_sensors[:, np.newaxis]
    
    # From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks, Muhammad Saad Zia et al.
    # UEs (and, in our case, targets) positions are generated as a homogeneous Poisson Point Process
    def gen_vehicle_pos(self, no_warning=False):
        cell_area = np.pi*self.data["CELL_RANGE"]**2
        n_ues = np.ceil(np.random.poisson(self.data["UE_DENSITY"]*cell_area, (self.data["REALIZATIONS"],)))
        n_targets = np.ceil(np.random.poisson(self.data["TARGET_DENSITY"]*cell_area, (self.data["REALIZATIONS"],)))
        if np.any(n_ues == 0) and self.data["UE_DENSITY"] > 0:
            if not no_warning:
                print("Warning: Some realizations have zero UEs. Consider increasing the UE density. Adding 1 UE to them...")
            n_ues[n_ues == 0] = 1
        if np.any(n_targets == 0) and self.data["TARGET_DENSITY"] > 0:
            if not no_warning:
                print("Warning: Some realizations have zero targets. Consider increasing the target density. Adding 1 target to them...")
            n_targets[n_targets == 0] = 1
        max_n_ues = int(np.max(n_ues))
        max_n_targets = int(np.max(n_targets))
        self.data["vehicle_range"] =  np.random.uniform(10, self.data["CELL_RANGE"], (self.data["REALIZATIONS"], max_n_ues + max_n_targets))
        self.data["vehicle_angle"] = np.random.uniform(0, 2*np.pi, (self.data["REALIZATIONS"], max_n_ues + max_n_targets))
        self.data["vehicle_x"] = self.data["vehicle_range"] * np.cos(self.data["vehicle_angle"])
        self.data["vehicle_y"] = self.data["vehicle_range"] * np.sin(self.data["vehicle_angle"])

        idx = np.arange(max_n_ues + max_n_targets)
        self.data["ue_mask"] = idx < n_ues[:, np.newaxis]
        self.data["target_mask"] = (idx >= n_ues[:, np.newaxis]) & (idx < (n_ues + n_targets)[:, np.newaxis])
        self.data["vehicle_mask"] = self.data["ue_mask"] | self.data["target_mask"]
    
    def gen_vehicle_fading(self):
        self.data["vehicle_fading"] = db2lin(np.random.normal(loc=0, scale=self.data["SHADOWING_STD_DEV"], size=self.data["vehicle_x"].shape))
    
    def gen_vehicle_sensor_fading_mat(self):
        self.data["vehicle_sensor_fading_mat"] = db2lin(np.random.normal(loc=0, scale=self.data["SHADOWING_STD_DEV"], size=self.data["vehicle_sensor_distance_mat"].shape))

    def gen_sensor_fading(self):
        self.data["sensor_fading"] = db2lin(np.random.normal(loc=0, scale=self.data["SHADOWING_STD_DEV"], size=self.data["sensor_x"].shape))
    
    # From 3GPP TR 38.901, Section 7.7.2, for the RCS of a vehicle
    def gen_rcs_term_s(self):
        # Sigma_s is log-normally distributed with a mean of 0 dB and a standard deviation of 3.41 dB
        sigma_s_std_dev_db = 3.41
        sigma_s_mean_db = -np.log(10)/20 * sigma_s_std_dev_db**2
        self.data["sigma_s_db_mat"] = np.random.normal(sigma_s_mean_db, sigma_s_std_dev_db, size=self.data["bistatic_angle_mat"].shape)

    # ----------------------------------------------
    # MASKS
    # ----------------------------------------------

    # Valid vehicle-sensor pairs
    def der_vehicle_sensor_mask(self):
        self.data["vehicle_sensor_mask"] = self.data["vehicle_mask"][:, :, np.newaxis] & self.data["sensor_mask"][:, np.newaxis, :]
    
    # ----------------------------------------------
    # BEAM ALLOCATION 
    # ----------------------------------------------
    def dec_beam_allocation_forced_full(self):
        self.data["vehicle_beam_allocation"] = self.data["vehicle_mask"] * self.data["FORCED_SLOT_ALLOCATION"]
        self.data["sensor_beam_allocation"] = self.data["sensor_mask"] * self.data["FORCED_SLOT_ALLOCATION"]
    
    def dec_beam_allocation_vehicles_full(self):
        beams_slots_per_sector = self.data["N_BEAMS_PER_SECTOR"]*self.data["SLOTS_PER_FRAME"]
        # Defining the sector of each vehicle
        sector_boresights = np.linspace(0, 2*np.pi, self.data["N_SECTORS"], endpoint=False) + np.deg2rad(30) # Adding an offset to match 3GPP TR 38.901, Table 7.8-1
        vehicle_sector_angle_diff = self.data["vehicle_angle"][:, :, np.newaxis] - sector_boresights[np.newaxis, np.newaxis, :]
        vehicle_in_sector = np.abs(np.mod(vehicle_sector_angle_diff + np.pi, 2*np.pi) - np.pi) < self.data["sector_angle_aperture"]/2 # Shape: [realization, vehicle, sector]
        vehicle_in_sector = vehicle_in_sector & (self.data["vehicle_mask"][:, :, np.newaxis]) # Only considering the vehicles that exist in each realization
        # Number of available beam slots, assuming each vehicle needs to receive at least 1 beam slot in a frame
        available_beam_slots = beams_slots_per_sector - vehicle_in_sector.sum(axis=1) # Shape: [realization, sector]
        if np.any(available_beam_slots < 0):
            print("Warning: Some sectors have more vehicles than available beams slots. Consider decreasing the vehicle density.")
        vehicles_per_sector = np.sum(self.data["vehicle_mask"][:, :, np.newaxis] & vehicle_in_sector, axis=1) # Shape: [realization, sector]
        beams_per_vehicle = np.floor( # Shape: [realization, sector]
            np.divide(
                available_beam_slots.astype(float),
                vehicles_per_sector.astype(float),
                out=np.zeros_like(available_beam_slots.astype(float)),
                where=vehicles_per_sector > 0,
            )
        )
        max_beams_per_target = self.data["COHERENCE_INTERVAL_DURATION"] // (self.data["OFDM_SYMBOLS_PER_SLOT"])
        beams_per_target = np.minimum(beams_per_vehicle, max_beams_per_target)
        beam_assignment = beams_per_target[:, np.newaxis, :] * (self.data["target_mask"][:, :, np.newaxis] & vehicle_in_sector)
        remaining_beams = beams_slots_per_sector - beam_assignment.sum(axis=1) # Shape: [realization, sector]
        ues_per_sector = np.sum(self.data["ue_mask"][:, :, np.newaxis] & vehicle_in_sector, axis=1) # Shape: [realization, sector]
        beams_per_ue = np.floor( # Shape: [realization, sector]
            np.divide(
                remaining_beams.astype(float),
                ues_per_sector.astype(float),
                out=np.zeros_like(available_beam_slots.astype(float)),
                where=ues_per_sector > 0,
            )
        )
        beam_assignment += beams_per_ue[:, np.newaxis, :] * (self.data["ue_mask"][:, :, np.newaxis] & vehicle_in_sector)
        remaining_beams = beams_slots_per_sector - beam_assignment.sum(axis=1) # Shape: [realization, sector]
        # Distributing the remaining beams (if any) to the UEs in a round-robin manner
        ue_counter = np.cumsum(self.data["ue_mask"][:, :, np.newaxis] & vehicle_in_sector, axis=1) - 1 # Shape: [realization, vehicle, sector]
        ue_counter = np.where(self.data["ue_mask"][:, :, np.newaxis] & vehicle_in_sector, ue_counter, np.inf) # Shape: [realization, vehicle, sector]
        ue_gets_extra_beam = (ue_counter < remaining_beams[:, np.newaxis, :]) & (self.data["ue_mask"][:, :, np.newaxis] & vehicle_in_sector) # Shape: [realization, vehicle, sector]
        beam_assignment += ue_gets_extra_beam.astype(int)
        # Reducing the beam assignment to the shape [realization, vehicle]
        beam_assignment = np.sum(beam_assignment, axis=2) # Shape: [realization, vehicle]
        # Clipping the maximum number of slots for a vehicle to guarantee it does not have multiple beams in the same slot
        self.data["vehicle_beam_allocation"] = np.minimum(beam_assignment, self.data["SLOTS_PER_FRAME"])
    
    def dec_beam_allocation_sensors_orthogonal(self):
        max_beam_slot_per_sensor = self.data["SLOTS_PER_FRAME"]
        interfering_sensors = ( # Shape: [realization, sensor, sensor]
            self.data["interfering_sensors_mat"]
            & self.data["sensor_mask"][:, np.newaxis, :]
            & self.data["sensor_mask"][:, :, np.newaxis]
        )
        sensors_per_beam = interfering_sensors.sum(axis=2)
        beam_slots = np.divide( # Shape: [realization, sensor]
            max_beam_slot_per_sensor,
            sensors_per_beam,
            out=np.zeros(
                sensors_per_beam.shape,
                dtype=float,
            ),
            where=sensors_per_beam[:, :] > 0,
        )
        # Shape: [realization, sensor, sensor]
        allocation = interfering_sensors * beam_slots[:, :, np.newaxis]
        allocation = np.where(allocation == 0, np.inf, allocation)
        # Shape: [realization, sensor]
        orthogonal_beam_slots = np.min(allocation, axis=1)
        orthogonal_beam_slots = np.where(
            np.isinf(orthogonal_beam_slots),
            0,
            orthogonal_beam_slots,
        )
        self.data["sensor_beam_allocation"] = (
            np.floor(orthogonal_beam_slots)
            * self.data["sensor_mask"]
        )


    # ----------------------------------------------
    # BANDWIDTH ALLOCATION 
    # ----------------------------------------------

    def dec_bandwidth_allocation(self, target=0, ue_sens=0, ue_comm=0, uplink=0):
        target_sensing_bandwidth = target*self.data["PRB_SIZE_HZ"]*self.data["target_mask"][..., np.newaxis]
        ue_sensing_bandwidth = ue_sens*self.data["PRB_SIZE_HZ"]*self.data["ue_mask"][..., np.newaxis]
        self.data["vehicle_sensing_band"] = target_sensing_bandwidth + ue_sensing_bandwidth
        self.data["vehicle_comm_band"] = ue_comm*self.data["PRB_SIZE_HZ"]*self.data["ue_mask"][..., np.newaxis]
        self.data["sensor_uplink_band"] = uplink*self.data["PRB_SIZE_HZ"]*self.data["sensor_mask"][..., np.newaxis]
        self.data["sens_portions"] = target/self.data["N_PRBS"]

    def dec_bandwidth_allocation_orthogonal_split_equal(
        self,
        alloc_decisions=[(0.3, 1), (0.5, 1), (0.7, 1)],
        no_interf_targets_use_full_band=False,
    ):
        self.data["sens_portions"] = np.array([a[0] for a in alloc_decisions])
        uplink_prbs = np.array([a[1] for a in alloc_decisions])
        self.data["total_dl_prbs"] = self.data["N_PRBS"] - uplink_prbs
        
        dl_comm_prbs = self.data["total_dl_prbs"] * (1 - self.data["sens_portions"])

        interfering_ues = ( # Shape: [realization, vehicle, vehicle]
            self.data["interfering_vehicles_mat"]
            & self.data["ue_mask"][:, np.newaxis, :]
            & self.data["ue_mask"][:, :, np.newaxis]
        )

        ues_per_beam = interfering_ues.sum(axis=2)
        
        beam_prbs = np.divide( # Shape: [realization, vehicle, alloc_decision]
            dl_comm_prbs[None, None, :],
            ues_per_beam[:, :, None],
            out=np.zeros(
                (*ues_per_beam.shape, len(dl_comm_prbs)),
                dtype=float,
            ),
            where=ues_per_beam[:, :, None] > 0,
        )

        # Shape: [realization, vehicle, vehicle, alloc_decision]
        allocation = interfering_ues[..., np.newaxis] * beam_prbs[:, :, np.newaxis, :]
        allocation = np.where(allocation == 0, np.inf, allocation)

        # Shape: [realization, vehicle, alloc_decision]
        orthogonal_comm_prbs = np.min(allocation, axis=1)
        orthogonal_comm_prbs = np.where(
            np.isinf(orthogonal_comm_prbs),
            0,
            orthogonal_comm_prbs,
        )

        if no_interf_targets_use_full_band:
            # Targets can use all the sensing bandwidth if they do not interfere with any UE
            interfering_targets = ( # Shape: [realization, vehicle, vehicle]
                self.data["interfering_vehicles_mat"]
                & self.data["target_mask"][:, :, np.newaxis]
                & self.data["ue_mask"][:, np.newaxis, :]
            )
            non_interfering_targets = self.data["target_mask"] & (np.sum(interfering_targets, axis=2) == 1) # Shape: [realization, vehicle]
            
            self.data["vehicle_sensing_band"] = (
                np.round(self.data["total_dl_prbs"] * self.data["sens_portions"])
                * self.data["PRB_SIZE_HZ"]
                * self.data["vehicle_mask"][..., np.newaxis]
                * (1 - non_interfering_targets[..., np.newaxis])
            )

            self.data["vehicle_sensing_band"] += (
                np.round(self.data["total_dl_prbs"])
                * self.data["PRB_SIZE_HZ"]
                * self.data["vehicle_mask"][..., np.newaxis]
                * non_interfering_targets[..., np.newaxis]
            )
        else:
            self.data["vehicle_sensing_band"] = (
                np.round(self.data["total_dl_prbs"] * self.data["sens_portions"])
                * self.data["PRB_SIZE_HZ"]
                * self.data["vehicle_mask"][..., np.newaxis]
            )

        self.data["vehicle_comm_band"] = (
            np.round(orthogonal_comm_prbs)
            * self.data["PRB_SIZE_HZ"]
            * self.data["vehicle_mask"][..., np.newaxis]
        )

    def dec_sensor_bandwidth_allocation_orthogonal_split_equal(self, uplink_prbs=[4]):
        uplink_prbs = np.array(uplink_prbs)
        interfering_sensors = ( # Shape: [realization, sensor, sensor]
            self.data["interfering_sensors_mat"]
            & self.data["sensor_mask"][:, np.newaxis, :]
            & self.data["sensor_mask"][:, :, np.newaxis]
        )
        sensors_per_beam = interfering_sensors.sum(axis=2)
        beam_prbs = np.divide( # Shape: [realization, sensor, alloc_decision]
            uplink_prbs[np.newaxis, np.newaxis, :],
            sensors_per_beam[:, :, np.newaxis],
            out=np.zeros(
                (*sensors_per_beam.shape, len(uplink_prbs)),
                dtype=float,
            ),
            where=sensors_per_beam[:, :, np.newaxis] > 0,
        )
        # Shape: [realization, sensor, sensor, alloc_decision]
        allocation = interfering_sensors[..., np.newaxis] * beam_prbs[:, :, np.newaxis, :]
        allocation = np.where(allocation == 0, np.inf, allocation)
        # Shape: [realization, sensor, alloc_decision]
        orthogonal_comm_prbs = np.min(allocation, axis=1)
        orthogonal_comm_prbs = np.where(
            np.isinf(orthogonal_comm_prbs),
            0,
            orthogonal_comm_prbs,
        )
        self.data["sensor_uplink_band"] = (
            np.round(orthogonal_comm_prbs)
            * self.data["PRB_SIZE_HZ"]
            * self.data["sensor_mask"][..., np.newaxis]
        )
    
    # ----------------------------------------------
    # INTERFERENCE INDICATORS 
    # ----------------------------------------------

    def der_interfering_vehicles_mat_angles(self):
        # Matrix with the differences in angles between all pairs of vehicles, in radians, in [0, 2*pi]
        angle_diffs = np.abs(
            self.data["vehicle_angle"][:, :, np.newaxis]
            - self.data["vehicle_angle"][:, np.newaxis, :]
        )
        # Matrix indicating pairs of vehicles with possibly overlapping beams (according to angles)
        self.data["interfering_vehicles_mat"] = (
            (
                angle_diffs
                < self.data["vehicle_half_beamwidth"][:, :, np.newaxis]
            )
            & self.data["vehicle_mask"][:, np.newaxis, :]
            & self.data["vehicle_mask"][:, :, np.newaxis]
        )
    
    def der_interfering_sensors_mat_angles(self):
        # Matrix with the differences in angles between all pairs of sensors, in radians, in [0, 2*pi]
        angle_diffs = np.abs(
            self.data["sensor_angle"][:, :, np.newaxis]
            - self.data["sensor_angle"][:, np.newaxis, :]
        )
        # Matrix indicating pairs of sensors with possibly overlapping beams (according to angles)
        self.data["interfering_sensors_mat"] = (
            (
                angle_diffs
                < self.data["sensor_half_beamwidth"][:, :, np.newaxis]
            )
            & self.data["sensor_mask"][:, np.newaxis, :]
            & self.data["sensor_mask"][:, :, np.newaxis]
        )
    
    def der_interfering_vehicles_mat_beam_allocation(self):
        # If the overlapping beams can be allocated in different slots, they do not interfere with each other
        interfering_time_mat = self.data["interfering_vehicles_mat"] * self.data["vehicle_beam_allocation"][:, np.newaxis, :]
        interfering_time_mat = np.sum(interfering_time_mat, axis = 2) > self.data["SLOTS_PER_FRAME"]
        # Updating the interfering vehicles matrix to consider the beam allocation
        self.data["interfering_vehicles_mat"] =  self.data["interfering_vehicles_mat"] * interfering_time_mat[:,:,np.newaxis]
        # We consider that a vehicle "interferes with itself" to simplify future bandwidth allocations
        self.data["interfering_vehicles_mat"] = self.data["interfering_vehicles_mat"].astype(bool) | np.eye(self.data["interfering_vehicles_mat"].shape[1])[np.newaxis, :, :].astype(bool)
    
    def der_interfering_sensors_mat_beam_allocation(self):
        # If the overlapping beams can be allocated in different slots, they do not interfere with each other
        interfering_time_mat = self.data["interfering_sensors_mat"] * self.data["sensor_beam_allocation"][:, np.newaxis, :] # Shape: [realization, sensor, sensor]
        interfering_time_mat = np.sum(interfering_time_mat, axis = 2) > self.data["SLOTS_PER_FRAME"]
        # Updating the interfering sensors matrix to consider the beam allocation
        self.data["interfering_sensors_mat"] =  self.data["interfering_sensors_mat"] * interfering_time_mat[:,:,np.newaxis]
        # We consider that a sensor "interferes with itself" to simplify future bandwidth allocations
        self.data["interfering_sensors_mat"] = self.data["interfering_sensors_mat"].astype(bool) | np.eye(self.data["interfering_sensors_mat"].shape[1])[np.newaxis, :, :].astype(bool)


    # ----------------------------------------------
    # GEOMETRIES 
    # ----------------------------------------------

    def der_vehicle_sensor_distance_mat(self):
        self.data["vehicle_sensor_distance_mat"] = np.hypot(
            self.data["vehicle_x"][:, :, np.newaxis] - self.data["sensor_x"][:, np.newaxis, :],
            self.data["vehicle_y"][:, :, np.newaxis] - self.data["sensor_y"][:, np.newaxis, :]
        )

    # Angle of targets relative to sensors' boresights, in radians, in [0, 2*pi]
    def der_vehicle_sensor_angle_mat(self):
        front_angle = angle_relative_to_boresight(
            self.data["vehicle_x"][:, :, np.newaxis],
            self.data["vehicle_y"][:, :, np.newaxis],
            self.data["sensor_x"][:, np.newaxis, :],
            self.data["sensor_y"][:, np.newaxis, :],
            self.data["sensor_boresights"][:, np.newaxis, :]
        )
        back_angle = angle_relative_to_boresight(
            self.data["vehicle_x"][:, :, np.newaxis],
            self.data["vehicle_y"][:, :, np.newaxis],
            self.data["sensor_x"][:, np.newaxis, :],
            self.data["sensor_y"][:, np.newaxis, :],
            self.data["sensor_boresights"][:, np.newaxis, :]-np.pi
        )
        self.data["vehicle_sensor_angle_mat"] = np.minimum(front_angle, back_angle)
        

    def der_sector_angle_aperture(self):
        self.data["sector_angle_aperture"] = 2*np.pi/self.data["N_SECTORS"]
    
    def der_sensor_angle_aperture(self):
        self.data["sensor_angle_aperture"] = 2*np.pi/2 # Assuming a single ULA

    def der_vehicle_sector_angle(self):
        rel_angles = angle_relative_to_boresight( # Shape: [realization, vehicle, boresight]
            np.zeros_like(self.data["vehicle_x"][..., np.newaxis]),
            np.zeros_like(self.data["vehicle_y"][..., np.newaxis]),
            self.data["vehicle_x"][..., np.newaxis],
            self.data["vehicle_y"][..., np.newaxis],
            self.data["BS_BORESIGHTS"][np.newaxis, np.newaxis, :] 
        )
        self.data["vehicle_sector_angle"] = np.min(rel_angles, axis=2) # Shape: [realization, vehicle]

    def der_sensor_sector_angle(self):
        rel_angles = angle_relative_to_boresight( # Shape: [realization, sensor, bs_boresights]
            np.zeros_like(self.data["sensor_x"][..., np.newaxis]),
            np.zeros_like(self.data["sensor_y"][..., np.newaxis]),
            self.data["sensor_x"][..., np.newaxis],
            self.data["sensor_y"][..., np.newaxis],
            self.data["BS_BORESIGHTS"][np.newaxis, np.newaxis, :] 
        )
        self.data["sensor_sector_angle"] = np.min(rel_angles, axis=2) # Shape: [realization, sensor]
    
    # Angle of the BS relative to the sensor's boresight, in radians, in [0, 2*pi]
    def der_bs_sensor_angle(self):
        front_angle = angle_relative_to_boresight( # Shape: [realization, sensor, sensor_boresights]
            self.data["sensor_x"],
            self.data["sensor_y"],
            np.zeros_like(self.data["sensor_x"]),
            np.zeros_like(self.data["sensor_y"]),
            self.data["sensor_boresights"] 
        )
        back_angle = angle_relative_to_boresight( # Shape: [realization, sensor, sensor_boresights]
            self.data["sensor_x"],
            self.data["sensor_y"],
            np.zeros_like(self.data["sensor_x"]),
            np.zeros_like(self.data["sensor_y"]),
            self.data["sensor_boresights"] - np.pi
        )
        self.data["bs_sensor_angle"] = np.minimum(front_angle, back_angle) # Shape: [realization, sensor]

    def der_bistatic_angle_mat(self):
        v_bs_x = -self.data["vehicle_x"][..., np.newaxis]
        v_bs_y = -self.data["vehicle_y"][..., np.newaxis]
        v_sensor_x = (self.data["sensor_x"][:, np.newaxis, :] - self.data["vehicle_x"][..., np.newaxis])
        v_sensor_y = (self.data["sensor_y"][:, np.newaxis, :] - self.data["vehicle_y"][..., np.newaxis])
        dot = v_bs_x*v_sensor_x + v_bs_y*v_sensor_y
        norm_bs = np.sqrt(v_bs_x**2 + v_bs_y**2)
        norm_sensor = np.sqrt(v_sensor_x**2 + v_sensor_y**2)
        self.data["bistatic_angle_mat"] = np.arccos(
            np.clip(dot/(norm_bs*norm_sensor), -1.0, 1.0)
        )

    # ----------------------------------------------
    # NOISE POWER 
    # ----------------------------------------------
    
    # From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks
    def _noise_power(self, bandwidth):
        # If bandwidth is 0, set it to the whole bandwidth in the system to avoid log(0)
        bandwidth = np.where(bandwidth == 0, self.data["BANDWIDTH_HZ"], bandwidth)
        return db2lin(-174 + 10 * np.log10(bandwidth) + self.data["NOISE_FIGURE_DB"])
    
    def der_vehicle_sensing_noise_power(self):
        self.data["vehicle_sensing_noise_power"] = self._noise_power(self.data["vehicle_sensing_band"])
    
    def der_vehicle_comm_noise_power(self):
        self.data["vehicle_comm_noise_power"] = self._noise_power(self.data["vehicle_comm_band"])
    
    def der_sensor_comm_noise_power(self):
        self.data["sensor_comm_noise_power"] = self._noise_power(self.data["sensor_uplink_band"])


    # ----------------------------------------------
    # SENSING CHANNEL
    # ----------------------------------------------

    # From 3GPP TR 38.901, Section 7.7.2, for the RCS of a single scattered point in the roof of the vehicle
    # Adapted to the 2D scenario removing the term with sigma^v and sigma^H from the sigma_MD_db calculation
    def der_vehicle_rcs_mat(self):
        G_max = 13.55
        sigma_max = 20.42
        k1 = 6
        k2 = 1.65
        sigma_md_db = np.maximum(
            G_max - k1 * np.sin(k2*self.data["bistatic_angle_mat"]/2) + 5 * np.log10(np.cos(self.data["bistatic_angle_mat"]/2)),
            G_max - sigma_max
        )
        self.data["rcs_db_mat"] = self.data["sigma_s_db_mat"] + sigma_md_db


    # From Fundamentals of Radar Signal Processing, 3rd edition, Mark A. Richards
    # Adaptated for bistatic sensing
    def der_vehicle_sensing_pl_mat(self):
        self.data["vehicle_sensing_pl_mat"] = (
            (4*np.pi)**3
            * self.data["vehicle_range"][:, :, np.newaxis]**self.data["PATH_LOSS_EXP"]
            * self.data["vehicle_sensor_distance_mat"]**self.data["PATH_LOSS_EXP"]
            / (self.data["WAVELENGTH"]**2)
            / db2lin(self.data["rcs_db_mat"])
            * self.data["vehicle_fading"][..., np.newaxis]
            * self.data["vehicle_sensor_fading_mat"]
        )
    
    # Adaptation of matched filter for slot allocation in OFDM systems
    def der_vehicle_processing_gain(self):
        # From A Novel Joint Angle-Range-Velocity Estimation Method for MIMO-OFDM ISAC Systems
        self.data["vehicle_processing_gain"] = (
            np.array(self.data["vehicle_sensing_band"])
            / self.data["SUBCARRIER_SPACING_HZ"] # Bandwidth -> Number of subcarriers
            * self.data["N_SENSOR_ANTENNA_ELEMENTS"]
            * np.minimum(
                self.data["COHERENCE_INTERVAL_DURATION"],
                self.data["OFDM_SYMBOLS_PER_SLOT"]
                * self.data["vehicle_beam_allocation"][..., np.newaxis] # Add alloc_decision
            )
        )

    # From Fundamentals of Radar Signal Processing, 3rd edition, Mark A. Richards
    # Adapted to include Rayleigh fading
    # Shape: [realization, vehicle, alloc_decision, sensor]
    def der_vehicle_sensing_snr_mat(self):
        self.data["vehicle_sensing_snr_mat"] = (
            self.data["vehicle_processing_gain"][..., np.newaxis]
            * db2lin(self.data["BS_BEAM_POWER_DB"])
            * self.data["vehicle_peak_beam_gain"][..., np.newaxis, np.newaxis] # Add alloc_decision and sensor
            * self.data["vehicle_sensor_peak_beam_gain_mat"][..., np.newaxis, :] # Add alloc_decision
            / self.data["vehicle_sensing_pl_mat"][..., np.newaxis, :] # Add alloc_decision
            / self.data["vehicle_sensing_noise_power"][..., np.newaxis]
        )
        # If SNR = 0 (because sensing bandwidth is 0), set it to NaN
        self.data["vehicle_sensing_snr_mat"] = np.where(
            self.data["vehicle_sensing_snr_mat"] == 0,
            np.nan,
            self.data["vehicle_sensing_snr_mat"],
        )

    # ----------------------------------------------
    # SENSING PERFORMANCE
    # ----------------------------------------------
    
    # From Fundamentals of Radar Signal Processing, 3rd edition, Mark A. Richards
    # Shape: [realization, vehicle, alloc_decision, sensor]
    def der_vehicle_range_error_mat(self):
        self.data["vehicle_range_error_mat"] = np.where(
            self.data["vehicle_sensing_band"][..., np.newaxis] > 0,
            SPEED_OF_LIGHT/(
                4*np.pi
                *self.data["vehicle_sensing_band"][..., np.newaxis]
                *np.sqrt(2*self.data["vehicle_sensing_snr_mat"])
            ),
            np.inf
        )

    # From Fundamentals of Radar Signal Processing, 3rd edition, Mark A. Richards
    # Angle error relative to the sensor
    def der_vehicle_angle_error_mat(self):
        angle_error = np.sqrt(
            6
            *self.data["WAVELENGTH"]**2
            /(
                (2*np.pi)**2
                * self.data["SENSOR_ANTENNA_SPACING"]**2
                * np.maximum(
                    np.cos(np.deg2rad(90 + self.data["TARGET_SENSOR_ANGLE_CORRECTION_DEG"]))**2,
                    np.cos(self.data["vehicle_sensor_angle_mat"][..., np.newaxis, :])**2 # Add alloc_decision
                ) 
                * self.data["vehicle_sensing_snr_mat"]
                * self.data["N_SENSOR_ANTENNA_ELEMENTS"]
                *(self.data["N_SENSOR_ANTENNA_ELEMENTS"]**2 - 1)
            )
        )
        angle_error = np.nan_to_num(angle_error, nan=np.inf)
        self.data["vehicle_angle_error_mat"] = np.clip(angle_error, 0, np.pi)

    
    # Distance from estimated position to true position, relative to the sensor tracking the UE or target
    def der_vehicle_position_error_mat(self):
        pos_error = np.sqrt(
            np.power(self.data["vehicle_range_error_mat"], 2)
            + (
                np.power(self.data["vehicle_sensor_distance_mat"][..., np.newaxis, :], 2)
                * np.power(
                    self.data["vehicle_angle_error_mat"],
                    2
                )
            )
        )
        pos_error = np.nan_to_num(pos_error, nan=np.inf)
        self.data["vehicle_position_error_mat"] = np.clip(pos_error, 0, self.data["CELL_RANGE"])

    # ----------------------------------------------
    # BEAMFORMING
    # ----------------------------------------------

    # From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks, Muhammad Saad Zia et al.
    def _peak_beamforming_gain(self, azimuth):
        peak_gain_elem_db = (
            self.data["MAX_ANTENNA_ELEMENT_GAIN_DB"]
            - np.minimum(
                12 * (
                    azimuth
                    /np.deg2rad(self.data["SINGLE_ELEMENT_HPBW_DEG"])
                )**2,
                self.data["FRONT_TO_BACK_RATIO_DB"]
            )
        )
        return self.data["N_ANTENNA_ELEMENTS"] * db2lin(peak_gain_elem_db)
    
    def der_vehicle_peak_beam_gain(self): 
        self.data["vehicle_peak_beam_gain"] = self._peak_beamforming_gain(self.data["vehicle_sector_angle"])
    
    def der_sensor_bs_peak_beam_gain(self):
        self.data["sensor_bs_peak_beam_gain"] = self._peak_beamforming_gain(self.data["sensor_sector_angle"])
    
    def der_bs_sensor_peak_beam_gain(self):
        self.data["bs_sensor_peak_beam_gain"] = self._peak_beamforming_gain(self.data["bs_sensor_angle"])

    def der_vehicle_sensor_peak_beam_gain_mat(self):
        self.data["vehicle_sensor_peak_beam_gain_mat"] = self._peak_beamforming_gain(self.data["vehicle_sensor_angle_mat"])

    # From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks, Muhammad Saad Zia et al.
    def der_sidelobe_gain(self):
        self.data["sidelobe_gain"] = 1.0/(self.data["N_ANTENNA_ELEMENTS"] * (np.sin(3*np.pi/(2*self.data["N_ANTENNA_ELEMENTS"])))**2)

    # From Antenna Theory Analysis and Design, 3rd edition, Table 6.2
    def der_broadside_hpbw(self):
        self.data["broadside_hpbw"] = np.pi - 2*np.arccos(1.391*self.data["WAVELENGTH"]/(np.pi*self.data["N_ANTENNA_ELEMENTS"]*self.data["ANTENNA_SPACING"]))

    # From Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks, Muhammad Saad Zia et al. 
    def _half_mainlobe_beamwidth(self, azimuth):
        phi_a = self.data["broadside_hpbw"]
        g1 = self._peak_beamforming_gain(azimuth)
        g2 = self.data["sidelobe_gain"]
        # Debug RuntimeWarning for the sqrt
        if np.any((10/3)*np.log10(g1/g2) < 0):
            idx = np.where((10/3)*np.log10(g1/g2) < 0)
            print(f"g1: {g1[idx]}, g2: {g2}, log: {np.log10(g1[idx]/g2)}, phi_a: {phi_a}")
        beamwidth = phi_a/2 * np.sqrt((10/3)*np.log10(g1/g2))
        return beamwidth

    def der_min_max_half_beamwidth(self):
        self.data["min_half_beamwidth"] = self._half_mainlobe_beamwidth(np.pi/self.data["N_SECTORS"])
        self.data["max_half_beamwidth"] = self._half_mainlobe_beamwidth(0)

    def der_vehicle_half_beamwidth(self):
        self.data["vehicle_half_beamwidth"] = self._half_mainlobe_beamwidth(self.data["vehicle_sector_angle"])
    
    def der_sensor_half_beamwidth(self):
        self.data["sensor_half_beamwidth"] = self._half_mainlobe_beamwidth(self.data["sensor_sector_angle"])
    
    # From TR 38.901, Table 7.3-1 and Effects of SNR-Dependent Beam Alignment Errors on Millimeter-Wave Cellular Networks, Muhammad Saad Zia et al.    
    def der_vehicle_beamforming_gain_mat(self):
        use_sidelobe = self.data["vehicle_angle_error_mat"] > self.data["vehicle_half_beamwidth"][..., np.newaxis, np.newaxis]
        bs_angle_error = np.arctan(self.data["vehicle_position_error_mat"]/self.data["vehicle_range"][..., np.newaxis, np.newaxis])
        self.data["vehicle_gain_degradation_db_mat"] = -3*(2*bs_angle_error/self.data["vehicle_half_beamwidth"][..., np.newaxis, np.newaxis])**2
        self.data["vehicle_beamforming_gain_mat"] = use_sidelobe*self.data["sidelobe_gain"] + (1-use_sidelobe) * self.data["vehicle_peak_beam_gain"][..., np.newaxis, np.newaxis] * db2lin(self.data["vehicle_gain_degradation_db_mat"])

    # ----------------------------------------------
    # SENSING RESOLUTION
    # ----------------------------------------------

    # From A Novel Joint Angle-Range-Velocity Estimation Method for MIMO-OFDM ISAC Systems
    def der_range_resolution(self):
        self.data["range_resolution"] = np.divide( # [alloc_decision]
            SPEED_OF_LIGHT,
            (2*self.data["sens_portions"]*self.data["BANDWIDTH_HZ"]),
            where=self.data["sens_portions"] > 0,
            out=np.full_like(self.data["sens_portions"], np.inf)
        )
    
    # From A Novel Joint Angle-Range-Velocity Estimation Method for MIMO-OFDM ISAC Systems
    def der_angular_resolution(self):
        self.data["angular_resolution"] = self.data["WAVELENGTH"] / (self.data["N_SENSOR_ANTENNA_ELEMENTS"] * self.data["ANTENNA_SPACING"])

    # From Fundamentals of Radar Signal Processing, 3rd edition, Mark A. Richards
    # Adapted to calculate the area, not the volume, and to directly use the angle resolution instead of the main lobe beamwidth 
    def der_resolution_cell_area(self):
        self.data["resolution_cell_area"] = self.data["range_resolution"] * self.data["angular_resolution"]*self.data["CELL_RANGE"] # [alloc_decision]

    # Upper-bound for resolved vehicles
    def der_max_resolved_vehicles(self):
        self.data["max_resolved_vehicles"] = np.divide( # [alloc_decision]
            np.pi * self.data["CELL_RANGE"]**2,
            self.data["resolution_cell_area"],
            where=self.data["resolution_cell_area"] > 0,
            out=np.zeros_like(self.data["resolution_cell_area"], dtype=float)
        )

    # Assuming the selection of resolved vehicles is random and uniform
    def der_unresolution_rates(self):
        n_vehicles = self.data["vehicle_mask"].sum(axis=1) # Shape: [realization]
        n_ues = self.data["ue_mask"].sum(axis=1) # Shape: [realization]
        n_targets = self.data["target_mask"].sum(axis=1) # Shape: [realization]
        ue_vehicles_ratio = np.divide( # Shape: [realization]
            n_ues,
            n_vehicles,
            where=n_vehicles > 0,
            out=np.zeros_like(n_ues, dtype=float)
        )
        target_vehicles_ratio = np.divide( # Shape: [realization]
            n_targets,
            n_vehicles,
            where=n_vehicles > 0,
            out=np.zeros_like(n_targets, dtype=float)
        )
        n_unresolved_vehicles = np.maximum(n_vehicles[:, np.newaxis] - self.data["max_resolved_vehicles"], 0) # Shape: [realization, alloc_decision]
        self.data["unresolved_vehicles_rate"] = np.divide( # Shape: [realization, alloc_decision]
            n_unresolved_vehicles,
            n_vehicles[:, np.newaxis],
            where=n_vehicles[:, np.newaxis] > 0,
            out=np.zeros_like(n_unresolved_vehicles, dtype=float)
        )
        # Shapes: [realization, alloc_decision]
        self.data["unresolved_ues_rate"] = ue_vehicles_ratio[:, np.newaxis] * self.data["unresolved_vehicles_rate"]
        self.data["unresolved_targets_rate"] = target_vehicles_ratio[:, np.newaxis] * self.data["unresolved_vehicles_rate"]



    # ----------------------------------------------
    # COMMUNICATION CHANNEL
    # ----------------------------------------------

    # From TR 38.901, Table 7.4.1-1
    # Worst case (always before the breakpoint distance)
    def _comm_pl(self, range, height_1, height_2, scenario="LOS_UMi_StreetCanyon"):
        breakpoint_distance = 4*height_1*height_2*self.data["CARRIER_FREQ_HZ"]/SPEED_OF_LIGHT
        distance_3d = np.sqrt(range**2 + (height_1 - height_2)**2)
        before_breakpoint = distance_3d < breakpoint_distance
        if scenario == "LOS_UMi_StreetCanyon":
            loss_before_breakpoint_db = (
                32.4
                + 21 * np.log10(distance_3d)
                + 20 * np.log10(self.data["CARRIER_FREQ_HZ"]/1e9)
            )
            loss_after_breakpoint_db = (
                32.4
                + 40 * np.log10(distance_3d)
                + 20 * np.log10(self.data["CARRIER_FREQ_HZ"]/1e9)
                - 9.5 * np.log10(breakpoint_distance**2 + (height_1 - height_2)**2)
            )
            loss_db = np.where(before_breakpoint, loss_before_breakpoint_db, loss_after_breakpoint_db)
        else:
            raise NotImplementedError(f"Scenario {scenario} not implemented")
        return db2lin(loss_db)
    
    def der_vehicle_comm_pl(self, scenario="LOS_UMi_StreetCanyon"):
        self.data["vehicle_comm_pl"] = (
            self._comm_pl(self.data["vehicle_range"], self.data["BS_HEIGHT"], self.data["VEHICLE_HEIGHT"], scenario)
            * self.data["vehicle_fading"]
        )
        
    def der_sensor_comm_pl(self, scenario="LOS_UMi_StreetCanyon"):
        self.data["sensor_comm_pl"] = (
            self._comm_pl(
                self.data["sensor_range"],
                self.data["BS_HEIGHT"],
                self.data["SENSOR_HEIGHT"],
                scenario
            )
            * self.data["sensor_fading"]
        )

    def _comm_snr(self, tx_gain, rx_gain, comm_pl, noise_power):
        return (
            db2lin(self.data["BS_BEAM_POWER_DB"])
            * tx_gain
            * rx_gain
            / comm_pl
            / noise_power
        )
    
    def der_vehicle_side_lobe_comm_snr(self):
        self.data["vehicle_side_lobe_comm_snr"] = self._comm_snr( # Shape: [realization, vehicle, alloc_decision]
            self.data["sidelobe_gain"], 
            db2lin(self.data["UE_GAIN_DB"]),
            self.data["vehicle_comm_pl"][..., np.newaxis], # Add alloc_decision
            self.data["vehicle_comm_noise_power"]
        )

    def der_vehicle_comm_snr_mat(self):
        self.data["vehicle_comm_snr_mat"] = self._comm_snr(
            self.data["vehicle_beamforming_gain_mat"],
            db2lin(self.data["UE_GAIN_DB"]),
            self.data["vehicle_comm_pl"][..., np.newaxis, np.newaxis], # Add alloc_decision and sensor
            self.data["vehicle_comm_noise_power"][..., np.newaxis] # Add sensor
        )

    def der_sensor_comm_snr(self):
        self.data["sensor_comm_snr"] = self._comm_snr(
            # db2lin(self.data["SENSOR_GAIN_DB"]),
            self.data["bs_sensor_peak_beam_gain"][..., np.newaxis], # Gain from sensor -> BS
            self.data["sensor_bs_peak_beam_gain"][..., np.newaxis], # Gain from BS -> sensor
            self.data["sensor_comm_pl"][..., np.newaxis],
            self.data["sensor_comm_noise_power"] # Shape: [realization, sensor, alloc_decision]
        )

    # ----------------------------------------------
    # COMMUNICATION PERFORMANCE
    # ----------------------------------------------

    def der_vehicle_side_lobe_thr(self):
        self.data["vehicle_side_lobe_thr"] = (
            self.data["vehicle_beam_allocation"][..., np.newaxis,]/self.data["SLOTS_PER_FRAME"] # Fraction of the frame where the vehicle is scheduled to receive data
            * self.data["vehicle_comm_band"]
            * np.log2(1 + self.data["vehicle_side_lobe_comm_snr"])
        )

    def der_vehicle_comm_thr_mat(self):
        self.data["vehicle_comm_thr_mat"] = (
            self.data["vehicle_beam_allocation"][..., np.newaxis, np.newaxis]/self.data["SLOTS_PER_FRAME"] # Fraction of the frame where the vehicle is scheduled to receive data
            * self.data["vehicle_comm_band"][..., np.newaxis]
            * np.log2(1 + self.data["vehicle_comm_snr_mat"])
        )
    
    def der_sensor_comm_thr(self):
        self.data["sensor_comm_thr"] = (
            self.data["sensor_beam_allocation"][..., np.newaxis]/self.data["SLOTS_PER_FRAME"] # Fraction of the frame where the vehicle is scheduled to receive data
            * self.data["sensor_uplink_band"]
            * np.log2(1 + self.data["sensor_comm_snr"])
        )

    # ----------------------------------------------
    # SLICE PERFORMANCE
    # ----------------------------------------------

    def der_vehicle_comm_slad_mat(self):
        self.data["vehicle_comm_slad_mat"] = (
            np.maximum(
                 self.data["REQ_THROUGHPUT"] - self.data["vehicle_comm_thr_mat"],
                0
            )
            / self.data["REQ_THROUGHPUT"]
        )*self.data["ue_mask"][..., np.newaxis, np.newaxis]
    
    def der_vehicle_sensing_slad_mat(self):
        self.data["vehicle_sensing_slad_mat"] = (
            np.maximum(
                self.data["vehicle_position_error_mat"] - self.data["REQ_POSITION_ERROR"],
                0
            )
            / (
                self.data["CELL_RANGE"]
                - self.data["REQ_POSITION_ERROR"]
            )
        ) * self.data["target_mask"][..., np.newaxis, np.newaxis]
    
    def der_comm_sla_satisfied_mat(self):
        self.data["comm_sla_satisfied_mat"] = (
            (self.data["vehicle_comm_thr_mat"] >= self.data["REQ_THROUGHPUT"])
            * self.data["ue_mask"][..., np.newaxis, np.newaxis]
        )

    def der_sensing_sla_satisfied_mat(self):
        self.data["sensing_sla_satisfied_mat"] = (
            (self.data["vehicle_position_error_mat"] <= self.data["REQ_POSITION_ERROR"])
            * self.data["target_mask"][..., np.newaxis, np.newaxis]
        )
    
    def der_side_lobe_comm_sla_satisfied(self):
        self.data["side_lobe_comm_sla_satisfied"] = ( # [realization, vehicle, alloc_decision]
            (self.data["vehicle_side_lobe_thr"] >= self.data["REQ_THROUGHPUT"])
            * self.data["ue_mask"][..., np.newaxis]
        )
    
    def der_side_lobe_comm_ssr(self):
        n_ues = np.sum(self.data["ue_mask"][..., np.newaxis], axis=1)
        total_satisfied = np.sum(self.data["side_lobe_comm_sla_satisfied"], axis=1)
        self.data["side_lobe_comm_ssr"] = np.divide(
            total_satisfied,
            n_ues,
            out=np.ones_like(total_satisfied, dtype=float),
            where=n_ues > 0,
        )
    # ----------------------------------------------
    # SENSOR ASSIGNMENT
    # ----------------------------------------------

    def dec_assign_sensor_lowest_position_error(self):
        self.data["vehicle_sensor_assignment"] = np.argmin(
            np.where(
                self.data["vehicle_sensor_mask"][..., np.newaxis, :], # [realization, vehicle, sensor] -> [realization, vehicle, alloc_decision, sensor]
                self.data["vehicle_position_error_mat"], # [realization, vehicle, alloc_decision, sensor]
                np.inf # Ignore non-assignable pairs
            ), axis=-1
        )

    def der_apply_assignments(self):
        
        # Indexing terms with shape [realizations, vehicle, alloc_decision]
        realization_idx = np.arange(self.data["REALIZATIONS"])[:, np.newaxis, np.newaxis]
        vehicle_idx = np.arange(self.data["vehicle_mask"].shape[1])[np.newaxis, :, np.newaxis]
        alloc_decision_idx = np.arange(self.data["vehicle_sensing_band"].shape[2])[np.newaxis, np.newaxis, :]
        assignment_idx = self.data["vehicle_sensor_assignment"] # Already has shape [realizations, vehicle, alloc_decision]
        
        # Reducing the sensor dimension on parameters with shape [realizations, vehicle, sensor]
        idx_term = (realization_idx, vehicle_idx, assignment_idx)
        self.data["vehicle_sensor_peak_beam_gain"] = self.data.pop("vehicle_sensor_peak_beam_gain_mat")[idx_term]
        self.data["vehicle_sensor_distance"] = self.data.pop("vehicle_sensor_distance_mat")[idx_term]
        self.data["vehicle_sensor_angle"] = self.data.pop("vehicle_sensor_angle_mat")[idx_term]
        self.data["vehicle_sensing_pl"] = self.data.pop("vehicle_sensing_pl_mat")[idx_term]
        self.data["bistatic_angle"] = self.data["bistatic_angle_mat"][idx_term]
        self.data["sigma_s_db"] = self.data.pop("sigma_s_db_mat")[idx_term]
        self.data["rcs_db"] = self.data.pop("rcs_db_mat")[idx_term]
        self.data["vehicle_sensor_fading"] = self.data.pop("vehicle_sensor_fading_mat")[idx_term]

        # Reducing the sensor dimension on parameters with shape [realizations, vehicle, alloc_decision, sensor]
        idx_term = (realization_idx, vehicle_idx, alloc_decision_idx, assignment_idx)
        self.data["vehicle_sensing_snr"] = self.data.pop("vehicle_sensing_snr_mat")[idx_term]
        self.data["vehicle_range_error"] = self.data.pop("vehicle_range_error_mat")[idx_term]
        self.data["vehicle_angle_error"] = self.data.pop("vehicle_angle_error_mat")[idx_term]
        self.data["vehicle_position_error"] = self.data.pop("vehicle_position_error_mat")[idx_term]
        self.data["vehicle_gain_degradation_db"] = self.data.pop("vehicle_gain_degradation_db_mat")[idx_term]
        self.data["vehicle_beamforming_gain"] = self.data.pop("vehicle_beamforming_gain_mat")[idx_term]
        self.data["vehicle_comm_snr"] = self.data.pop("vehicle_comm_snr_mat")[idx_term]
        self.data["vehicle_comm_thr"] = self.data.pop("vehicle_comm_thr_mat")[idx_term]
        self.data["vehicle_comm_slad"] = self.data.pop("vehicle_comm_slad_mat")[idx_term]
        self.data["vehicle_sensing_slad"] = self.data.pop("vehicle_sensing_slad_mat")[idx_term]
        self.data["comm_sla_satisfied"] = self.data.pop("comm_sla_satisfied_mat")[idx_term]
        self.data["sensing_sla_satisfied"] = self.data.pop("sensing_sla_satisfied_mat")[idx_term]

    # ----------------------------------------------
    # SENSOR DEMAND
    # ----------------------------------------------

    def der_sensor_demand(self):
        n_sensors = self.data["sensor_mask"].shape[1]
        assignments = np.where( # [realization, vehicle, alloc_decision]
            self.data["vehicle_mask"][..., np.newaxis] & (self.data["vehicle_sensing_band"] > 0), # [realization, vehicle, alloc_decision]
            self.data["vehicle_sensor_assignment"], # [realization, vehicle, alloc_decision]
            np.nan
        )
        sensor_counts = ( # [realization, alloc_decision, sensor]
            assignments[..., np.newaxis]
            == np.arange(n_sensors)
        ).sum(axis=1)
        # Changing the axis order to [realization, sensor, alloc_decision]
        sensor_counts = np.moveaxis(sensor_counts, 2, 1)
        self.data["sensor_demand_vehicles"] = sensor_counts
        self.data["sensor_demand"] = self.data["sensor_demand_vehicles"] * self.data["SENSING_DEMAND_PER_VEHICLE"]

    def der_sensor_demand_satisfied(self):
        self.data["sensor_demand_satisfied"] = self.data["sensor_comm_thr"] >= self.data["sensor_demand"]
    
    def der_sensor_demand_satisfaction_ratio(self, no_sensor_demand_warning = False):
        self.data["sensor_demand_satisfaction_ratio"] = np.divide(
            np.sum(self.data["sensor_demand_satisfied"]*self.data["sensor_mask"][...,np.newaxis], axis=1),
            np.sum(self.data["sensor_mask"], axis=1)[..., np.newaxis]
        )
        if not no_sensor_demand_warning and np.any(self.data["sensor_demand_satisfaction_ratio"] < 1):
            print(f"Warning: Some sensors have unsatisfied demand. Consider increasing the sensor uplink bandwidth. Current sensor density: {self.data['SENSOR_DENSITY']*1e6:.0f} sensors/km^2")
            unsatisfied_sensors = np.where(~self.data["sensor_demand_satisfied"])
            print(unsatisfied_sensors)

    def der_successfully_transmitted_vehicles_ratio(self):
        n_vehicles = self.data["vehicle_mask"].sum(axis=1) # Shape: [realization]
        sensor_capacity_vehicles = np.floor(self.data["sensor_comm_thr"] / self.data["SENSING_DEMAND_PER_VEHICLE"]) # Shape: [realization, sensor, alloc_decision]
        n_successfully_transmitted_vehicles = np.minimum(sensor_capacity_vehicles, self.data["sensor_demand_vehicles"]).sum(axis=1) # Shape: [realization, alloc_decision]
        self.data["successfully_transmitted_vehicles_ratio"] = np.divide( # Shape: [realization, alloc_decision]
            n_successfully_transmitted_vehicles,
            n_vehicles[:, np.newaxis],
            where=n_vehicles[:, np.newaxis] > 0,
            out=np.ones_like(n_successfully_transmitted_vehicles, dtype=float)
        )
    
    # ----------------------------------------------
    # PERFORMANCE METRICS
    # ----------------------------------------------

    def der_sensing_capacity(self):
        self.data["sensing_capacity"] = (1-self.data["unresolved_vehicles_rate"]) * self.data["successfully_transmitted_vehicles_ratio"]

    def der_ue_peak_thr_alloc_decision(self):
        self.data["ue_peak_thr_alloc_decision"] = np.argmax(
            self.data["vehicle_comm_thr"], # [realization, vehicle, alloc_decision]
            axis=2,
        ).astype(int) # [realization, vehicle]
        self.data["ue_peak_thr_alloc_decision"] = self.data["ue_peak_thr_alloc_decision"] * self.data["ue_mask"] # [realization, vehicle]

    def der_sensing_ssr(self):
        n_targets = np.sum(self.data["target_mask"][..., np.newaxis], axis=1)
        total_satisfied = np.sum(self.data["sensing_sla_satisfied"], axis=1)
        sensing_ssr_all_resolved = np.divide(
            total_satisfied,
            n_targets,
            out=np.ones_like(total_satisfied, dtype=float),
            where=n_targets > 0,
        )
        self.data["sensing_ssr"] = sensing_ssr_all_resolved * self.data["sensing_capacity"]


    def der_comm_ssr(self):
        n_ues = np.sum(self.data["ue_mask"][..., np.newaxis], axis=1)
        total_satisfied = np.sum(self.data["comm_sla_satisfied"], axis=1)
        comm_ssr_all_resolved = np.divide( # Shape: [realization, alloc_decision] 
            total_satisfied,
            n_ues,
            out=np.ones_like(total_satisfied, dtype=float),
            where=n_ues > 0,
        )
        self.data["comm_ssr"] = (
            comm_ssr_all_resolved * self.data["sensing_capacity"] # Only the resolved UEs can satisfy the SLA
            + self.data["side_lobe_comm_ssr"] * (1-self.data["sensing_capacity"]) # The unresolved UEs can only satisfy the SLA with the side lobe throughput
        )

    def der_ssr(self):
        self.data["ssr"] = (
            self.data["COMM_SLICE_WEIGHT"] * self.data["comm_ssr"]
            + self.data["SENSING_SLICE_WEIGHT"] * self.data["sensing_ssr"]
        )
    
    def der_mean_target_position_estimation_error(self): # Shape: [realization, alloc_decision]
        n_targets = np.sum(self.data["target_mask"][..., np.newaxis], axis=1)
        total_error = np.sum(self.data["vehicle_position_error"]*self.data["target_mask"][..., np.newaxis], axis=1)
        mean_target_position_estimation_error_all_resolved = np.divide(
            total_error,
            n_targets,
            out=np.zeros_like(total_error, dtype=float),
            where=n_targets > 0,
        )
        self.data["mean_target_position_estimation_error"] = (
            mean_target_position_estimation_error_all_resolved * self.data["sensing_capacity"]
            + self.data["CELL_RANGE"] * (1-self.data["sensing_capacity"]) # The unresolved targets are assumed to have the worst-case position estimation error, which is the cell range
        )
    
    def der_mean_ue_comm_thr(self): # Shape: [realization, alloc_decision]
        n_ues = np.sum(self.data["ue_mask"][..., np.newaxis], axis=1)
        total_thr_all_resolved = np.sum(self.data["vehicle_comm_thr"]*self.data["ue_mask"][..., np.newaxis], axis=1)
        total_thr_no_resolved = np.sum(self.data["vehicle_side_lobe_thr"]*self.data["ue_mask"][..., np.newaxis], axis=1)
        mean_ue_comm_thr_all_resolved = np.divide(
            total_thr_all_resolved,
            n_ues,
            out=np.zeros_like(total_thr_all_resolved, dtype=float),
            where=n_ues > 0,
        )
        mean_ue_comm_thr_no_resolved = np.divide(
            total_thr_no_resolved,
            n_ues,
            out=np.zeros_like(total_thr_no_resolved, dtype=float),
            where=n_ues > 0,
        )

        self.data["mean_ue_comm_thr"] = (
            mean_ue_comm_thr_all_resolved * self.data["sensing_capacity"]
            + mean_ue_comm_thr_no_resolved * (1-self.data["sensing_capacity"])
        )
    
    
